POST localhost:8080/add-article

{ "section":"автопарк",
  "subsection":"муслин",
  "article":{
    "author":"Нгуен Гок Ньян",
    "title":"Влияние политеха на аутизм",
    "body":"skdsdjfklsdgkdfjdsklfjsdfpososi"
  }
}